var data = [
	{
		"id": 1,
		"head": "Спорт",
		"headColor": "orange",
		"headIco": "ball-ico",
		"projectTile": "Встановлення дитячого майданчика на території гуртожитків CТEУ",
		"projectStatus": "Реалізований",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 1 день назад",
		"projectText": "Бюджет цІкавих ініціатив зростає. Пік активності припав",
		"avtorImg": "person-ico1.jpg",
		"avtorName": "Виктория Неделько",
		"budget":"5 000", 
		"vote": "5 532",
		"category":"sport",
		"city": "Днепр"
	},
	{
		"id": 2,
		"head": "Комунальне господарство",
		"headColor": "violet",
		"headIco":"tree-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "Неможливо реалізувати",
		"projectStatusColor": "impossible",
		"projectStatusSale": "подано 12.11.2015",
		"projectText": "Для нас стало приємною несподіванкою активність наших громадян щодо участі у проекті", 
		"avtorImg": "person-ico2.jpg", 
		"avtorName": "Любовь Бутко",
		"budget":"100 300",
		"vote": "10 057",
		"category":"community",
		"city": "Киев"
	},
	{
		"id": 3,
		"head": "Охорона здоров'я",
		"headColor": "pink",
		"headIco":"health-ico",
		"projectTile": "GPSAUTO \"система моніторинга транспорту\" ",
		"projectStatus": "Брав участь",
		"projectStatusColor": "participated",
		"projectStatusSale": "подано 28.01.2016", 
		"projectText": "Пік активності припав на останні 2 дні  прийому ініціатив, що спричинило технічне поштової",
		"avtorImg": "person-ico3.jpg",
		"avtorName": "Veselina Dashich",
		"budget":"750 000",
		"vote": "271 556",
		"category":"health",
		"city": "Днепр"
	},
	{
		"id": 4,
		"head": "Дорожнє господарство",
		"headColor": "blue",
		"headIco":"street-ico",
		"projectTile": "Встановлення дитячого майданчика на території гуртожитків CТEУ",
		"projectStatus": "Відхилений",
		"projectStatusColor": "rejected",
		"projectStatusSale": "подано 1 день назад", 
		"projectText": "Бюджет цІкавих ініціатив зростає Пік активності припав на останні прийому ініціатив, що спричинило",
		"avtorImg": "person-ico6.jpg",
		"avtorName": "Виктория Неделько",
		"budget":"5 000",
		"vote": "5 556",
		"category":"road",
		"city": "Киев"
	},
	{
		"id": 5,
		"head": "Навколишнє середовище",
		"headColor": "green",
		"headIco":"environment-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "Успішно пройшов оцінку",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 12.11.2015", 
		"projectText": "Для нас стало приємною несподіванкою активність наших громадян щодо участі у проекті",
		"avtorImg": "person-ico4.jpg",
		"avtorName": "Любовь Бутко",
		"budget":"100 300",
		"vote": "10 556",
		"category":"environment",
		"city": "Днепр"
	},
	{
		"id": 6,
		"head": "Освіта",
		"headColor": "lightBlue",
		"headIco":"education-ico",
		"projectTile": "GPSAUTO \"система моніторинга транспорту\" ",
		"projectStatus": "Відхилений",
		"projectStatusColor": "rejected",
		"projectStatusSale": "подано 12.11.2015", 
		"projectText": "Пік активності припав на останні 2 дні  прийому ініціатив, що спричинило технічне поштової",
		"avtorImg": "person-ico4.jpg",
		"avtorName": "Veselina Dashich",
		"budget":"750 300",
		"vote": "271 556",
		"category":"education",
		"city": "Киев"
	},
	{
		"id": 7,
		"head": "Засоби масової інформації",
		"headColor": "lightOrange",
		"headIco":"info-ico",
		"projectTile": "Встановлення дитячого майданчика на території гуртожитків CТEУ",
		"projectStatus": "Брав участь",
		"projectStatusColor": "participated",
		"projectStatusSale": "подано 12.11.2015", 
		"projectText": "Бюджет цІкавих ініціатив зростає Пік активності припав на останні прийому ініціатив, що спричинило",
		"avtorImg": "person-ico2.jpg",
		"avtorName": "Виктория Неделько",
		"budget":"250 000",
		"vote": "70 556",
		"category":"info",
		"city": "Днепр"
	},
	{
		"id": 8,
		"head": "Телекомунікації та ІТ",
		"headColor": "darkBlue",
		"headIco":"it-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "Переможець",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 12.11.2015", 
		"projectText": "Бюджет цІкавих ініціатив зростає Пік активності припав на останні прийому ініціатив, що спричинило",
		"avtorImg": "person-ico-default.jpg",
		"avtorName": "Бутко Олеся",
		"budget":"10 300",
		"vote": "1 556",
		"category":"it",
		"city": "Киев"
	},
	{
		"id": 9,
		"head": "Соціальний захист",
		"headColor": "semiPink",
		"headIco":"social-ico",
		"projectTile": "GPSAUTO \"система моніторинга транспорту\"",
		"projectStatus": "Реалізований",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 28.01.2015", 
		"projectText": "Пік активності припав на останні 2 дні  прийому ініціатив, що спричинило технічне поштової",
		"avtorImg": "person-ico5.jpg",
		"avtorName": "Олег Бутко",
		"budget":"330 300",
		"vote": "50 556",
		"category":"protect",
		"city": "Днепр"
	},
	{
		"id": 10,
		"head": "Спорт",
		"headColor": "orange",
		"headIco":"ball-ico",
		"projectTile": "Встановлення дитячого майданчика на території гуртожитків CТEУ",
		"projectStatus": "На реалізації",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 1.01.2015", 
		"projectText": "Бюджет цІкавих ініціатив зростає Пік активності припав на останні прийому ініціатив, що спричинило",
		"avtorImg": "person-ico-default.jpg",
		"avtorName": "Олег Бутко",
		"budget":"1 300",
		"vote": "4 556",
		"category":"sport",
		"city": "Днепр"
	},
	{
		"id": 11,
		"head": "Транспорт",
		"headColor": "darkViolet",
		"headIco":"bike-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "Брав участь",
		"projectStatusColor": "participated",
		"projectStatusSale": "подано 1.01.2015", 
		"projectText": "Для нас стало приємною несподіванкою активність наших громадян щодо участі у проекті",
		"avtorImg": "person-ico6.jpg",
		"avtorName": "Настя Мохито",
		"budget":"120 400",
		"vote": "20 556",
		"category":"transport",
		"city": "Киев"
	},
	{
		"id": 12,
		"head": "Велоінфраструктура",
		"headColor": "lightGreen",
		"headIco":"transport-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "Успішно пройшов оцінку",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 1.01.2015", 
		"projectText": "Для нас стало приємною несподіванкою активність наших громадян щодо участі у проекті",
		"avtorImg": "person-ico4.jpg",
		"avtorName": "Олег Мохито",
		"budget":"300 400",
		"vote": "100 556",
		"category":"bike",
		"city": "Днепр"
	},
	{
		"id": 13,
		"head": "громадський порядок",
		"headColor": "red",
		"headIco":"protect-ico",
		"projectTile": "Встановлення дитячого майданчика на території гуртожитків CТEУ",
		"projectStatus": "На розгляді",
		"projectStatusColor": "participated",
		"projectStatusSale": "подано 1 день назад", 
		"projectText": "Бюджет цІкавих ініціатив зростає Пік активності припав на останні прийому ініціатив, що спричинило",
		"avtorImg": "person-ico3.jpg",
		"avtorName": "Виктор Неделько",
		"budget":"30 400",
		"vote": "10 556",
		"category":"order",
		"city": "Киев"
	},
	{
		"id": 14,
		"head": "Енергозбереження",
		"headColor": "golden",
		"headIco":"energy-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "Переможець",
		"projectStatusColor": "done",
		"projectStatusSale": "подано 1 день назад", 
		"projectText": "Бюджет цІкавих ініціатив зростає Пік активності припав на останні прийому ініціатив, що спричинило",
		"avtorImg": "person-ico4.jpg",
		"avtorName": "Любов Неделько",
		"budget":"205 400",
		"vote": "101 556",
		"category":"energy",
		"city": "Киев"
	},
	{
		"id": 15,
		"head": "Культура та туризм",
		"headColor": "darkGreen",
		"headIco":"culture-ico",
		"projectTile": "Дитячий і спортивний майданчик у дворі будинку",
		"projectStatus": "На голосуванні",
		"projectStatusColor": "participated",
		"projectStatusSale": "подано 1 день назад", 
		"projectText": "Пік активності припав на останні 2 дні  прийому ініціатив, що спричинило технічне поштової",
		"avtorImg": "person-ico7.jpg",
		"avtorName": "Владислав Неделько",
		"budget":"800 400",
		"vote": "200 556",
		"category":"culture",
		"city": "Днепр"
	}
];